version: "3"

services:
  websergo:
    build: .
    ports:
      - 8080:8080

  nginx:
    image: nginx
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - 8888:80

  redis:
    image: redis:alpine
    expose:
      - 6379
